# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mType', models.CharField(max_length=200)),
                ('mCat', models.CharField(max_length=200)),
                ('mNbCat', models.IntegerField()),
                ('mID', models.CharField(max_length=200)),
                ('mTitleTP', models.CharField(max_length=200)),
                ('mOriginalTitleTP', models.CharField(max_length=200)),
                ('mCountryTP', models.CharField(max_length=200)),
                ('mYearTP', models.IntegerField()),
                ('mGenreTP', models.CharField(max_length=200)),
                ('mVotesTP', models.IntegerField()),
                ('mDescriptionTP', models.CharField(max_length=200)),
                ('mDirectorTP', models.CharField(max_length=200)),
                ('mActorsTP', models.CharField(max_length=200)),
                ('mIMGTP', models.CharField(max_length=250)),
                ('mIsIMDB', models.BooleanField(default=False)),
                ('mTitleI', models.CharField(max_length=200)),
                ('mYearI', models.IntegerField()),
                ('mDateReleaseI', models.CharField(max_length=200)),
                ('mDirectorI', models.CharField(max_length=200)),
                ('mActorsI', models.CharField(max_length=200)),
                ('mDescriptionI', models.CharField(max_length=200)),
                ('mCountryI', models.CharField(max_length=200)),
                ('mLanguageI', models.CharField(max_length=200)),
                ('mGenreI', models.CharField(max_length=200)),
                ('mRatingI', models.FloatField()),
                ('mVotesI', models.IntegerField()),
                ('mAwardsI', models.CharField(max_length=200)),
                ('mImgI', models.CharField(max_length=200)),
                ('mFormat1', models.CharField(max_length=200)),
                ('mFormat2', models.CharField(max_length=200)),
                ('mFormat3', models.CharField(max_length=200)),
                ('mFormat4', models.CharField(max_length=200)),
                ('mFormat5', models.CharField(max_length=200)),
                ('mFormat6', models.CharField(max_length=200)),
                ('mFormat7', models.CharField(max_length=200)),
                ('mFormat8', models.CharField(max_length=200)),
                ('mSeen', models.BooleanField(default=False)),
                ('mWhishlist', models.BooleanField(default=False)),
                ('mIMDBWrong', models.BooleanField(default=False)),
                ('mNew', models.BooleanField(default=True)),
                ('mDateUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
